[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "api"
  node_bundler = "esbuild"
  
[build.environment]
  NODE_VERSION = "20"

# THIS IS THE MISSING PIECE
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
